# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1340, 720)
        Dialog.setSizeGripEnabled(False)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1340, 720))
        self.widget.setStyleSheet("background-color: rgb(69, 69, 69);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(620, 20, 101, 51))
        self.label.setStyleSheet("font: 36pt \"Sans Serif\"; color:rgb(239, 239, 239)")
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 80, 1340, 80))
        self.widget_2.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(5, 5, 200, 70))
        self.widget_3.setStyleSheet("background-color: rgb(69, 69, 69);\n"
"border-radius: 20px;")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(5, 10, 190, 70))
        self.label_2.setStyleSheet("font: 36pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(210, 5, 200, 70))
        self.widget_4.setStyleSheet("background-color: rgb(69, 69, 69);\n"
"border-radius: 20px;")
        self.widget_4.setObjectName("widget_4")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(5, 10, 190, 70))
        self.label_4.setStyleSheet("font: 36pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(415, 5, 200, 70))
        self.widget_5.setStyleSheet("background-color: rgb(69, 69, 69);\n"
"border-radius: 20px;")
        self.widget_5.setObjectName("widget_5")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setGeometry(QtCore.QRect(5, 10, 190, 70))
        self.label_8.setStyleSheet("font: 36pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_8.setObjectName("label_8")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setGeometry(QtCore.QRect(10, 170, 1320, 540))
        self.widget_6.setStyleSheet("background-color: rgb(239, 239, 239);\n"
"border-radius: 20px;")
        self.widget_6.setObjectName("widget_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Template"))
        self.label.setText(_translate("Dialog", "Title"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Tab 1</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Tab 2</p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Tab 3</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
