# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verify_email.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginScreen(object):
    def setupUi(self, LoginScreen):
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.resize(1340, 720)
        LoginScreen.setSizeGripEnabled(False)
        self.widget = QtWidgets.QWidget(LoginScreen)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1340, 720))
        self.widget.setStyleSheet("background-color: rgb(69, 69, 69);")
        self.widget.setObjectName("widget")
        self.Title = QtWidgets.QLabel(self.widget)
        self.Title.setGeometry(QtCore.QRect(610, 20, 121, 51))
        self.Title.setStyleSheet("font: 36pt \"Sans Serif\"; color:rgb(239, 239, 239)")
        self.Title.setObjectName("Title")
        self.TabBar = QtWidgets.QWidget(self.widget)
        self.TabBar.setGeometry(QtCore.QRect(0, 80, 1340, 80))
        self.TabBar.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.TabBar.setObjectName("TabBar")
        self.SignUpTab = QtWidgets.QWidget(self.TabBar)
        self.SignUpTab.setGeometry(QtCore.QRect(5, 5, 200, 70))
        self.SignUpTab.setStyleSheet("border: 2px solid;\n"
"border-radius: 20px;\n"
"border-color:rgb(69, 69, 69);")
        self.SignUpTab.setObjectName("SignUpTab")
        self.SignUpText = QtWidgets.QLabel(self.SignUpTab)
        self.SignUpText.setGeometry(QtCore.QRect(0, 0, 200, 70))
        self.SignUpText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SignUpText.setStyleSheet("font: 36pt \"Sans Serif\"; color:rgb(69, 69, 69);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.SignUpText.setObjectName("SignUpText")
        self.LoginTab = QtWidgets.QWidget(self.TabBar)
        self.LoginTab.setGeometry(QtCore.QRect(210, 5, 200, 70))
        self.LoginTab.setStyleSheet("background-color: rgb(69, 69, 69);\n"
"border-radius: 20px;")
        self.LoginTab.setObjectName("LoginTab")
        self.LoginText = QtWidgets.QLabel(self.LoginTab)
        self.LoginText.setGeometry(QtCore.QRect(0, 0, 200, 70))
        self.LoginText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoginText.setStyleSheet("font: 36pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.LoginText.setObjectName("LoginText")
        self.ForgottenPasswordTab = QtWidgets.QWidget(self.TabBar)
        self.ForgottenPasswordTab.setGeometry(QtCore.QRect(415, 5, 200, 70))
        self.ForgottenPasswordTab.setStyleSheet("background-color: rgb(69, 69, 69);\n"
"border-radius: 20px;")
        self.ForgottenPasswordTab.setObjectName("ForgottenPasswordTab")
        self.ForgottenPasswordText = QtWidgets.QLabel(self.ForgottenPasswordTab)
        self.ForgottenPasswordText.setGeometry(QtCore.QRect(0, 0, 200, 70))
        self.ForgottenPasswordText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ForgottenPasswordText.setStyleSheet("font: 28pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.ForgottenPasswordText.setObjectName("ForgottenPasswordText")
        self.ResetPasswordTab = QtWidgets.QWidget(self.TabBar)
        self.ResetPasswordTab.setGeometry(QtCore.QRect(620, 6, 200, 70))
        self.ResetPasswordTab.setStyleSheet("background-color: rgb(69, 69, 69);\n"
"border-radius: 20px;")
        self.ResetPasswordTab.setObjectName("ResetPasswordTab")
        self.ResetPasswordText = QtWidgets.QLabel(self.ResetPasswordTab)
        self.ResetPasswordText.setGeometry(QtCore.QRect(0, 0, 200, 70))
        self.ResetPasswordText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ResetPasswordText.setStyleSheet("font: 28pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.ResetPasswordText.setObjectName("ResetPasswordText")
        self.MainWidget = QtWidgets.QWidget(self.widget)
        self.MainWidget.setGeometry(QtCore.QRect(10, 170, 1320, 540))
        self.MainWidget.setStyleSheet("background-color: rgb(239, 239, 239);\n"
"border-radius: 20px;")
        self.MainWidget.setObjectName("MainWidget")
        self.UsernameInput = QtWidgets.QLineEdit(self.MainWidget)
        self.UsernameInput.setGeometry(QtCore.QRect(620, 40, 231, 61))
        self.UsernameInput.setStyleSheet("border-color: rgb(69, 69, 69);\n"
"border: solid 2px;\n"
"background-color: rgb(69, 69, 69);\n"
"color: rgb(239, 239, 239);\n"
"font: 18pt \"Sans Serif\";")
        self.UsernameInput.setObjectName("UsernameInput")
        self.Username = QtWidgets.QLabel(self.MainWidget)
        self.Username.setGeometry(QtCore.QRect(410, 40, 181, 61))
        self.Username.setStyleSheet("font: 25pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"background-color: rgb(69, 69, 69); padding: 5px;")
        self.Username.setObjectName("Username")
        self.Email = QtWidgets.QLabel(self.MainWidget)
        self.Email.setGeometry(QtCore.QRect(410, 130, 181, 61))
        self.Email.setStyleSheet("font: 25pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"background-color: rgb(69, 69, 69); padding: 5px;")
        self.Email.setObjectName("Email")
        self.EmailInput = QtWidgets.QLineEdit(self.MainWidget)
        self.EmailInput.setGeometry(QtCore.QRect(620, 130, 231, 60))
        self.EmailInput.setStyleSheet("border-color: rgb(69, 69, 69);\n"
"border: solid 2px;\n"
"background-color: rgb(69, 69, 69);\n"
"color: rgb(239, 239, 239);\n"
"font: 18pt \"Sans Serif\";")
        self.EmailInput.setObjectName("EmailInput")
        self.Password = QtWidgets.QLabel(self.MainWidget)
        self.Password.setGeometry(QtCore.QRect(410, 220, 181, 61))
        self.Password.setStyleSheet("font: 25pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"background-color: rgb(69, 69, 69); padding: 5px;")
        self.Password.setObjectName("Password")
        self.PasswordInput = QtWidgets.QLineEdit(self.MainWidget)
        self.PasswordInput.setGeometry(QtCore.QRect(620, 220, 231, 60))
        self.PasswordInput.setStyleSheet("border-color: rgb(69, 69, 69);\n"
"border: solid 2px;\n"
"background-color: rgb(69, 69, 69);\n"
"color: rgb(239, 239, 239);\n"
"font: 18pt \"Sans Serif\";")
        self.PasswordInput.setObjectName("PasswordInput")
        self.VerifyPassword = QtWidgets.QLabel(self.MainWidget)
        self.VerifyPassword.setGeometry(QtCore.QRect(320, 310, 271, 61))
        self.VerifyPassword.setStyleSheet("font: 25pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"background-color: rgb(69, 69, 69); padding: 5px;")
        self.VerifyPassword.setObjectName("VerifyPassword")
        self.VerifyPasswordInput = QtWidgets.QLineEdit(self.MainWidget)
        self.VerifyPasswordInput.setGeometry(QtCore.QRect(620, 310, 231, 60))
        self.VerifyPasswordInput.setStyleSheet("border-color: rgb(69, 69, 69);\n"
"border: solid 2px;\n"
"background-color: rgb(69, 69, 69);\n"
"color: rgb(239, 239, 239);\n"
"font: 18pt \"Sans Serif\";")
        self.VerifyPasswordInput.setObjectName("VerifyPasswordInput")

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "Visualisation of the Riemann Hypothesis - Sign Up"))
        self.Title.setText(_translate("LoginScreen", "Login"))
        self.SignUpText.setText(_translate("LoginScreen", "<html><head/><body><p align=\"center\">Sign Up</p></body></html>"))
        self.LoginText.setText(_translate("LoginScreen", "<html><head/><body><p align=\"center\">Login</p></body></html>"))
        self.ForgottenPasswordText.setText(_translate("LoginScreen", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Forgotten<br>Password</span></p></body></html>"))
        self.ResetPasswordText.setText(_translate("LoginScreen", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Reset<br>Password</span></p></body></html>"))
        self.Username.setText(_translate("LoginScreen", "<html><head/><body><p align=\"center\">Username:</p></body></html>"))
        self.Email.setText(_translate("LoginScreen", "<html><head/><body><p align=\"center\">Email:</p></body></html>"))
        self.Password.setText(_translate("LoginScreen", "<html><head/><body><p align=\"center\">Password:</p></body></html>"))
        self.VerifyPassword.setText(_translate("LoginScreen", "<html><head/><body><p align=\"center\">Verify Password:</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginScreen = QtWidgets.QDialog()
    ui = Ui_LoginScreen()
    ui.setupUi(LoginScreen)
    LoginScreen.show()
    sys.exit(app.exec_())
