# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TemplateScreen(object):
    def setupUi(self, TemplateScreen):
        TemplateScreen.setObjectName("TemplateScreen")
        TemplateScreen.resize(1340, 720)
        TemplateScreen.setSizeGripEnabled(False)
        self.widget = QtWidgets.QWidget(TemplateScreen)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1340, 720))
        self.widget.setStyleSheet("background-color: rgb(69, 69, 69);")
        self.widget.setObjectName("widget")
        self.Title = QtWidgets.QLabel(self.widget)
        self.Title.setGeometry(QtCore.QRect(610, 20, 191, 51))
        self.Title.setStyleSheet("font: 36pt \"Sans Serif\"; color:rgb(239, 239, 239)")
        self.Title.setObjectName("Title")
        self.TabBar = QtWidgets.QWidget(self.widget)
        self.TabBar.setGeometry(QtCore.QRect(0, 80, 1340, 80))
        self.TabBar.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.TabBar.setObjectName("TabBar")
        self.Tab1 = QtWidgets.QPushButton(self.TabBar)
        self.Tab1.setGeometry(QtCore.QRect(10, 5, 200, 70))
        self.Tab1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tab1.setStyleSheet("border: 2px solid;\n"
"border-radius: 20px;\n"
"border-color:rgb(69, 69, 69);\n"
"background-color: rgb(239, 239, 239);\n"
"font: 18pt \"Sans Serif\"; color:rgb(69, 69, 69);\n"
"")
        self.Tab1.setObjectName("Tab1")
        self.Tab2 = QtWidgets.QPushButton(self.TabBar)
        self.Tab2.setGeometry(QtCore.QRect(220, 5, 200, 70))
        self.Tab2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tab2.setStyleSheet("border: 2px solid;\n"
"border-radius: 20px;\n"
"border-color:rgb(69, 69, 69);\n"
"background-color: rgb(69, 69, 69);\n"
"font: 18pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"")
        self.Tab2.setObjectName("Tab2")
        self.MainWidget = QtWidgets.QWidget(self.widget)
        self.MainWidget.setGeometry(QtCore.QRect(10, 170, 1320, 540))
        self.MainWidget.setStyleSheet("background-color: rgb(239, 239, 239);\n"
"border-radius: 20px;")
        self.MainWidget.setObjectName("MainWidget")
        self.PrevButton = QtWidgets.QPushButton(self.MainWidget)
        self.PrevButton.setGeometry(QtCore.QRect(10, 460, 200, 70))
        self.PrevButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PrevButton.setStyleSheet("border: 2px solid;\n"
"border-radius: 20px;\n"
"border-color:rgb(69, 69, 69);\n"
"background-color: rgb(69, 69, 69);\n"
"font: 18pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"")
        self.PrevButton.setObjectName("PrevButton")
        self.NextButton = QtWidgets.QPushButton(self.MainWidget)
        self.NextButton.setGeometry(QtCore.QRect(1110, 460, 200, 70))
        self.NextButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NextButton.setStyleSheet("border: 2px solid;\n"
"border-radius: 20px;\n"
"border-color:rgb(69, 69, 69);\n"
"background-color: rgb(69, 69, 69);\n"
"font: 18pt \"Sans Serif\"; color:rgb(239, 239, 239);\n"
"")
        self.NextButton.setObjectName("NextButton")
        self.MainText = QtWidgets.QLabel(self.MainWidget)
        self.MainText.setGeometry(QtCore.QRect(40, 80, 1251, 31))
        self.MainText.setStyleSheet("font: 13pt \"Sans Serif\"; color:rgb(69, 69, 69);\n"
"background-color: rgb(239, 239, 239); padding: 5px;")
        self.MainText.setWordWrap(True)
        self.MainText.setObjectName("MainText")
        self.SubTitleText = QtWidgets.QLabel(self.MainWidget)
        self.SubTitleText.setGeometry(QtCore.QRect(40, 20, 311, 41))
        self.SubTitleText.setStyleSheet("font: 25pt \"Sans Serif\"; color:rgb(69, 69, 69);\n"
"background-color: rgb(239, 239, 239); padding: 5px;")
        self.SubTitleText.setObjectName("SubTitleText")

        self.retranslateUi(TemplateScreen)
        QtCore.QMetaObject.connectSlotsByName(TemplateScreen)

    def retranslateUi(self, TemplateScreen):
        _translate = QtCore.QCoreApplication.translate
        TemplateScreen.setWindowTitle(_translate("TemplateScreen", "Visualising the Riemann Hypothesis - Template"))
        self.Title.setText(_translate("TemplateScreen", "Template"))
        self.Tab1.setText(_translate("TemplateScreen", "Tab1"))
        self.Tab2.setText(_translate("TemplateScreen", "Tab2"))
        self.PrevButton.setText(_translate("TemplateScreen", "Prev"))
        self.NextButton.setText(_translate("TemplateScreen", "Next"))
        self.MainText.setText(_translate("TemplateScreen", "<html><head/><body><p>This is the main body of each page</p></body></html>"))
        self.SubTitleText.setText(_translate("TemplateScreen", "<html><head/><body><p><span style=\" font-weight:600;\">Template</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TemplateScreen = QtWidgets.QDialog()
    ui = Ui_TemplateScreen()
    ui.setupUi(TemplateScreen)
    TemplateScreen.show()
    sys.exit(app.exec_())
