from .tutorial_notes import Ui_TutorialNotesScreen
from .introduction_notes import Ui_IntroductionNotesScreen
from .investigation_notes import Ui_InvestigationNotesScreen
from .summary_notes import Ui_SummaryNotesScreen
