# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mat_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MatPlotScreen(object):
    def setupUi(self, MatPlotScreen):
        MatPlotScreen.setObjectName("MatPlotScreen")
        MatPlotScreen.resize(1340, 720)
        MatPlotScreen.setSizeGripEnabled(False)

        self.retranslateUi(MatPlotScreen)
        QtCore.QMetaObject.connectSlotsByName(MatPlotScreen)

    def retranslateUi(self, MatPlotScreen):
        _translate = QtCore.QCoreApplication.translate
        MatPlotScreen.setWindowTitle(_translate("MatPlotScreen", "Visualising the Riemann Hypothesis - Zeta Zeroes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MatPlotScreen = QtWidgets.QDialog()
    ui = Ui_MatPlotScreen()
    ui.setupUi(MatPlotScreen)
    MatPlotScreen.show()
    sys.exit(app.exec_())
