# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/investigation_screens/polar_graph_mat_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PolarGraphMatPlotScreen(object):
    def setupUi(self, PolarGraphMatPlotScreen):
        PolarGraphMatPlotScreen.setObjectName("PolarGraphMatPlotScreen")
        PolarGraphMatPlotScreen.resize(1340, 720)
        PolarGraphMatPlotScreen.setSizeGripEnabled(False)

        self.retranslateUi(PolarGraphMatPlotScreen)
        QtCore.QMetaObject.connectSlotsByName(PolarGraphMatPlotScreen)

    def retranslateUi(self, PolarGraphMatPlotScreen):
        _translate = QtCore.QCoreApplication.translate
        PolarGraphMatPlotScreen.setWindowTitle(_translate("PolarGraphMatPlotScreen", "Visualising the Riemann Hypothesis - Polar Graph"))
