# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/tutorial_screens/graph_mat_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphMatPlotScreen(object):
    def setupUi(self, GraphMatPlotScreen):
        GraphMatPlotScreen.setObjectName("GraphMatPlotScreen")
        GraphMatPlotScreen.resize(1340, 720)
        GraphMatPlotScreen.setSizeGripEnabled(False)

        self.retranslateUi(GraphMatPlotScreen)
        QtCore.QMetaObject.connectSlotsByName(GraphMatPlotScreen)

    def retranslateUi(self, GraphMatPlotScreen):
        _translate = QtCore.QCoreApplication.translate
        GraphMatPlotScreen.setWindowTitle(_translate("GraphMatPlotScreen", "Visualising the Riemann Hypothesis - Tutorial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GraphMatPlotScreen = QtWidgets.QDialog()
    ui = Ui_GraphMatPlotScreen()
    ui.setupUi(GraphMatPlotScreen)
    GraphMatPlotScreen.show()
    sys.exit(app.exec_())
